name: myPlugin
version: '${project.version}'
main: me.reizora.dev.myplugin.MyPlugin
api-version: '1.20'
commands:
  setAFKTimer:
    description: Set the time for counting as AFK
    usage: /setAFKTimer <seconds>
  LavaFloor:
    description: The ground set you on Fire!
    usage: /LavaFloor